language: php

sudo: false

git:
    depth: 1

cache:
    directories:
        - $HOME/.composer

env:
    global:
        - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-progress"
        - COMPOSER_FLAGS=""

before_install:
    # turn off XDebug
    - phpenv config-rm xdebug.ini || return 0

    # Composer: boost installation
    - composer global show -ND 2>&1 | grep "hirak/prestissimo" || travis_retry composer global require $DEFAULT_COMPOSER_FLAGS hirak/prestissimo

jobs:
    include:
        -
            stage: Static Code Analysis
            php: 7.1
            env: COMPOSER_FLAGS="--no-dev --prefer-stable"
            install:
                - travis_retry composer update -d dev-tools $DEFAULT_COMPOSER_FLAGS
                - composer info -d dev-tools -D | sort

                - travis_retry composer update $DEFAULT_COMPOSER_FLAGS $COMPOSER_FLAGS
                - composer info -D | sort
            script:
                - ./check_trailing_spaces.sh || travis_terminate 1
                - ./dev-tools/vendor/bin/phpmd src,tests text phpmd.xml || travis_terminate 1
                - ./dev-tools/vendor/bin/composer-require-checker check composer.json || travis_terminate 1
                - ./dev-tools/vendor/bin/php-cs-fixer fix -v

        - &STANDARD_TEST_JOB
            stage: Test
            php: 5.4
            install:
                - travis_retry composer update $DEFAULT_COMPOSER_FLAGS $COMPOSER_FLAGS
                - composer info -D | sort
            script:
                - vendor/bin/phpunit --verbose

        -
            <<: *STANDARD_TEST_JOB
            php: 5.3
            env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
            dist: precise

        -
            <<: *STANDARD_TEST_JOB
            php: 5.5

        -
            <<: *STANDARD_TEST_JOB
            php: 5.6

        -
            <<: *STANDARD_TEST_JOB
            php: 7.0

        -
            <<: *STANDARD_TEST_JOB
            php: 7.1

        -
            <<: *STANDARD_TEST_JOB
            php: nightly
            env: SYMFONY_DEPRECATIONS_HELPER=weak
